"use client";

import React, { useState } from "react";
import { FolderClosed, FileText, Download, Sparkles, Check, Plus, BookOpen, Search } from "lucide-react";
import { Venture, VentureStore } from "@/lib/store/ventureStore";

export interface DocumentsTabProps {
  venture: Venture;
}

export interface CustomDoc {
  id: string;
  title: string;
  category: "Customer Interview" | "PRD" | "Market Research" | "Meeting Notes" | "Specification";
  content: string;
  date: string;
}

export function DocumentsTab({ venture }: DocumentsTabProps) {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [showAddModal, setShowAddModal] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newCategory, setNewCategory] = useState<CustomDoc["category"]>("Customer Interview");
  const [newContent, setNewContent] = useState("");
  const [customDocs, setCustomDocs] = useState<CustomDoc[]>([
    {
      id: "cd-1",
      title: "3 Founder Onboarding Interviews",
      category: "Customer Interview",
      content: "Founder 1: Onboarding took too many steps. Founder 2: Abandoned at workspace config. Founder 3: Loved the voice standup.",
      date: "August 2026",
    },
    {
      id: "cd-2",
      title: "Pricing & Willingness-to-Pay Research",
      category: "Market Research",
      content: "Solo founders prefer a $100 unlimited first-month trial or flat-rate pilot before committing to an annual subscription.",
      date: "August 2026",
    },
  ]);

  const defaultDocs = [
    {
      id: "doc-1",
      title: `${venture.name} — Executive Summary & BA Brief`,
      desc: "Complete analytical breakdown of market opportunity, target customer, and MVP roadmap.",
      date: "Generated by AI BA",
      type: "Markdown Dossier",
    },
    {
      id: "doc-2",
      title: `${venture.name} — Assumptions Register & Risk Matrix`,
      desc: `Full breakdown of ${venture.assumptions.length} tracked hypotheses, testing statuses, and logged evidence.`,
      date: "Live export",
      type: "Data Export",
    },
    {
      id: "doc-3",
      title: `${venture.name} — Product Requirements Document (PRD)`,
      desc: "Sprint features, user stories, acceptance criteria, and competitive differentiators.",
      date: "Sprint Active",
      type: "PRD Document",
    },
  ];

  const handleCreateDoc = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim() || !newContent.trim()) return;

    const newDoc: CustomDoc = {
      id: "cd-" + Date.now(),
      title: newTitle.trim(),
      category: newCategory,
      content: newContent.trim(),
      date: "Just now",
    };

    setCustomDocs([newDoc, ...customDocs]);
    setShowAddModal(false);
    setNewTitle("");
    setNewContent("");
  };

  const handleDownload = (id: string, title: string) => {
    setDownloadingId(id);
    setTimeout(() => {
      const assumptionsList = Array.isArray(venture?.assumptions) ? venture.assumptions : [];
      const assumptionsText = assumptionsList
        .map(
          (a, i) =>
            `${i + 1}. [${a.status?.toUpperCase() || "UNTESTED"}] (${a.category || "General"} / ${a.importance || "Medium"} Risk): ${a.statement}\n   Evidence: ${
              a.evidence || "Pending discovery"
            }`
        )
        .join("\n\n");

      const columnsObj = venture?.columns || {};
      const cardsText = Object.entries(columnsObj)
        .map(([colKey, col]: [string, any]) => {
          const colName = col?.name || colKey.toUpperCase();
          const items = Array.isArray(col) ? col : Array.isArray(col?.items) ? col.items : [];
          return (
            `### ${colName} (${items.length})\n` +
            items.map((item: any) => `- [${item.category || "Task"}] ${item.title} (${item.owner || "YOU"})`).join("\n")
          );
        })
        .join("\n\n");

      const content = `# ${venture.name} — Business Analyst Dossier
**Generated by FounderAlly AI Business Analyst**
**Date:** ${new Date().toLocaleDateString()}
**Status:** ${venture.status} | **Stage:** ${venture.stage}

---

## 1. Venture Overview
- **Tagline:** ${venture.tagline}
- **Target Customer (ICP):** ${venture.targetCustomer}
- **Problem Statement:** ${venture.problemStatement}
- **Proposed Solution:** ${venture.solutionSummary}

---

## 2. Market Sizing & Strategic Defensibility
- **TAM:** ${venture.strategy.tam}
- **SAM:** ${venture.strategy.sam}
- **SOM:** ${venture.strategy.som}
- **Core Moat:** ${venture.strategy.moat}
- **Existing Alternatives:** ${venture.strategy.alternatives}

---

## 3. Assumptions Register & Hypotheses
${assumptionsText || "No assumptions recorded yet."}

---

## 4. Current Sprint & Roadmap
${cardsText}
`;

      const blob = new Blob([content], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${venture.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-ba-dossier.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setDownloadingId(null);
    }, 600);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 animate-in fade-in duration-200">
      {/* 1. Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-blue-950 rounded-3xl p-6 sm:p-8 text-white shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/20 text-blue-200 border border-blue-400/30 text-xs font-bold">
            <BookOpen className="w-3.5 h-3.5" />
            <span>AI Knowledge Base</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black tracking-tight">
            Knowledge Your Business Analyst Can Use
          </h1>
          <p className="text-sm text-slate-300 max-w-2xl leading-relaxed">
            Store business plans, PRDs, customer interview notes, and research. Your selected advisor uses this knowledge base during daily stand-ups and sprint planning to substantiate decisions with evidence.
          </p>
        </div>

        <button
          onClick={() => setShowAddModal(true)}
          className="flex items-center justify-center gap-2 px-5 py-3 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold shadow-lg transition-all cursor-pointer shrink-0"
        >
          <Plus className="w-4 h-4" />
          <span>Add Knowledge Document</span>
        </button>
      </div>

      {/* 2. Custom Knowledge Documents Section */}
      <div className="space-y-3">
        <div className="flex items-center justify-between px-1">
          <h2 className="text-sm font-bold text-slate-900">
            Active Knowledge & Interview Transcripts ({customDocs.length})
          </h2>
          <span className="text-xs text-slate-500">Connected to the advisor retrieval pipeline</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {customDocs.map((doc) => (
            <div key={doc.id} className="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-xs space-y-3">
              <div className="flex items-start justify-between gap-2">
                <div>
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-indigo-50 text-indigo-700 border border-indigo-200">
                    {doc.category}
                  </span>
                  <h3 className="text-sm font-bold text-slate-900 mt-1.5">{doc.title}</h3>
                </div>
                <span className="text-[11px] text-slate-400 shrink-0">{doc.date}</span>
              </div>
              <p className="text-xs text-slate-600 line-clamp-3 bg-slate-50 p-3 rounded-xl border border-slate-100 font-mono">
                {doc.content}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* 3. Generated BA Dossiers */}
      <div className="space-y-3 pt-2">
        <div className="flex items-center justify-between px-1">
          <h2 className="text-sm font-bold text-slate-900">
            Generated BA Exports & System Dossiers
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {defaultDocs.map((doc) => {
            const isDownloading = downloadingId === doc.id;
            return (
              <div key={doc.id} className="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-xs flex flex-col justify-between space-y-4">
                <div className="space-y-2">
                  <div className="w-9 h-9 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center font-bold">
                    <FileText className="w-4 h-4" />
                  </div>
                  <h3 className="text-xs font-bold text-slate-900">{doc.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed">{doc.desc}</p>
                </div>
                <div className="pt-2 border-t border-slate-100 flex items-center justify-between">
                  <span className="text-[10px] text-slate-400 font-semibold">{doc.type}</span>
                  <button
                    onClick={() => handleDownload(doc.id, doc.title)}
                    disabled={isDownloading}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold transition-colors cursor-pointer"
                  >
                    {isDownloading ? (
                      <Check className="w-3.5 h-3.5 text-emerald-600 animate-pulse" />
                    ) : (
                      <Download className="w-3.5 h-3.5" />
                    )}
                    <span>{isDownloading ? "Exporting..." : "Export"}</span>
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Add Document Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 bg-slate-900/50 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl p-6 sm:p-7 max-w-lg w-full shadow-2xl space-y-4 animate-in zoom-in-95">
            <h3 className="text-base font-bold text-slate-900">Add Knowledge Document for Your Advisor</h3>
            <form onSubmit={handleCreateDoc} className="space-y-4">
              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Document Title</label>
                <input
                  type="text"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g. 5 Customer Discovery Interview Notes"
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-xs font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  required
                />
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Category</label>
                <select
                  value={newCategory}
                  onChange={(e) => setNewCategory(e.target.value as any)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-xs font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none"
                >
                  <option value="Customer Interview">Customer Interview</option>
                  <option value="PRD">PRD (Product Requirements)</option>
                  <option value="Market Research">Market Research & Pricing</option>
                  <option value="Meeting Notes">Meeting Notes</option>
                  <option value="Specification">Technical Specification</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Content / Transcript Notes</label>
                <textarea
                  value={newContent}
                  onChange={(e) => setNewContent(e.target.value)}
                  placeholder="Paste interview answers, quotes, customer pain points, or requirement notes here..."
                  rows={5}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-xs font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  required
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-4 py-2 rounded-xl text-xs font-bold text-slate-600 hover:bg-slate-100 cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold shadow-xs cursor-pointer"
                >
                  Save to Knowledge Base
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
