"use client";

import React, { useState } from "react";
import { FolderClosed, FileText, Download, Sparkles, Check, Share2 } from "lucide-react";
import { Venture } from "@/lib/store/ventureStore";

export interface DocumentsTabProps {
  venture: Venture;
}

export function DocumentsTab({ venture }: DocumentsTabProps) {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const docs = [
    {
      id: "doc-1",
      title: `${venture.name} — Executive Summary & BA Brief`,
      desc: "Complete analytical breakdown of market opportunity, target customer, and MVP roadmap.",
      date: "Generated just now by AI BA",
      type: "Markdown Dossier",
    },
    {
      id: "doc-2",
      title: `${venture.name} — Assumptions Register & Risk Matrix`,
      desc: `Full breakdown of ${venture.assumptions.length} tracked hypotheses, testing statuses, and logged evidence.`,
      date: "Live export",
      type: "Data Export",
    },
    {
      id: "doc-3",
      title: `${venture.name} — Product Requirements Document (PRD)`,
      desc: "Sprint features, user stories, acceptance criteria, and competitive differentiators.",
      date: "Sprint 2 Active",
      type: "PRD Document",
    },
  ];

  const handleDownload = (id: string, title: string) => {
    setDownloadingId(id);
    setTimeout(() => {
      const assumptionsList = Array.isArray(venture?.assumptions) ? venture.assumptions : [];
      const assumptionsText = assumptionsList
        .map(
          (a, i) =>
            `${i + 1}. [${a.status?.toUpperCase() || "UNTESTED"}] (${a.category || "General"} / ${a.importance || "Medium"} Risk): ${a.statement}\n   Evidence: ${
              a.evidence || "Pending discovery"
            }`
        )
        .join("\n\n");

      const columnsObj = venture?.columns || {};
      const cardsText = Object.entries(columnsObj)
        .map(([colKey, col]: [string, any]) => {
          const colName = col?.name || colKey.toUpperCase();
          const items = Array.isArray(col) ? col : Array.isArray(col?.items) ? col.items : [];
          return (
            `### ${colName} (${items.length})\n` +
            items.map((item: any) => `- [${item.category || "Task"}] ${item.title} (${item.owner || "YOU"})`).join("\n")
          );
        })
        .join("\n\n");

      const content = `# ${venture.name} — Business Analyst Dossier
**Generated by FounderAlly AI Business Analyst**
**Date:** ${new Date().toLocaleDateString()}
**Status:** ${venture.status} | **Stage:** ${venture.stage}

---

## 1. Venture Overview
- **Tagline:** ${venture.tagline}
- **Target Customer (ICP):** ${venture.targetCustomer}
- **Problem Statement:** ${venture.problemStatement}
- **Proposed Solution:** ${venture.solutionSummary}

---

## 2. Market Sizing & Strategic Defensibility
- **TAM:** ${venture.strategy.tam}
- **SAM:** ${venture.strategy.sam}
- **SOM:** ${venture.strategy.som}
- **Core Moat:** ${venture.strategy.moat}
- **Existing Alternatives:** ${venture.strategy.alternatives}

---

## 3. Assumptions Register & Hypotheses
${assumptionsText || "No assumptions recorded yet."}

---

## 4. Current Sprint & Roadmap
${cardsText}
`;

      const blob = new Blob([content], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${venture.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-ba-dossier.md`;
      a.click();
      URL.revokeObjectURL(url);
      setDownloadingId(null);
    }, 600);
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-10">
      {/* Header */}
      <div className="bg-white rounded-3xl p-6 border border-slate-200/90 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-xl bg-blue-50 text-blue-600">
              <FolderClosed className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-bold text-slate-900">
              Venture Documents — {venture.name}
            </h2>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Investor-ready dossiers, PRDs, and financial sheets compiled dynamically from your real venture data.
          </p>
        </div>

        <button
          onClick={() => handleDownload("full", `${venture.name}-Complete-Dossier`)}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-md shadow-blue-500/20 transition-all self-start sm:self-auto"
        >
          <Sparkles className="w-4 h-4" />
          <span>Export Full {venture.name} Dossier</span>
        </button>
      </div>

      {/* Documents Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {docs.map((doc) => (
          <div
            key={doc.id}
            className="bg-white rounded-3xl p-6 border border-slate-200/90 shadow-xs flex flex-col justify-between space-y-4 hover:border-slate-300 hover:shadow-xs transition-all"
          >
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="p-2.5 rounded-2xl bg-blue-50 text-blue-600">
                  <FileText className="w-5 h-5" />
                </div>
                <span className="text-[11px] font-bold px-2.5 py-0.5 rounded-full bg-slate-100 text-slate-600">
                  {doc.type}
                </span>
              </div>

              <div>
                <h3 className="font-bold text-slate-900 text-sm">{doc.title}</h3>
                <p className="text-xs text-slate-500 mt-1 leading-relaxed">{doc.desc}</p>
              </div>
            </div>

            <div className="pt-4 border-t border-slate-100 flex items-center justify-between">
              <span className="text-[10px] text-slate-400 font-medium">{doc.date}</span>
              <button
                onClick={() => handleDownload(doc.id, doc.title)}
                className="inline-flex items-center gap-1.5 text-xs font-bold text-blue-600 hover:text-blue-700 p-1.5 rounded-lg hover:bg-blue-50 transition-colors"
              >
                {downloadingId === doc.id ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Downloaded</span>
                  </>
                ) : (
                  <>
                    <Download className="w-3.5 h-3.5" />
                    <span>Download</span>
                  </>
                )}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
